### ISSUE TITLE
provide a way to use zemu with release binary

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/ledger-avalanche#217]
In order to support CI ledger integration and E2E efforts at CLI, it would be desirable to find a way to use use zemu directly with a release artifact. Currently zemu expects a .elf file, wich is not included (only installer shell scripts and source code eg https://github.com/ava-labs/ledger-avalanche/releases/tag/v0.7.2-hotfix).
So if posible either you can include .elf files in the release (and maybe generate the .hex to be loaded just from it). Or provide a way to generate an .elf (as expected from qemu) from the .hex in the installer scripts. If including .elf files, would be useful to have it retroactive to current ledger live release 0.7.0.

**Comment by becominginsane** [comment]
This is now present from the newest release, but as far as older release are concerned we wouldn't be able to retrieve the exact artifacts as they have expired already.

As a note, the app release done by ledger may slightly differ from our releases since they don't just take our release directly but instead recompile everything.
